CREATE TABLE IF NOT EXISTS `Message` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `chatId` INT NOT NULL,
  `role` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,  -- Replaced JSON with TEXT
  `createdAt` TIMESTAMP NOT NULL,
  FOREIGN KEY (`chatId`) REFERENCES `Chat`(`id`) ON DELETE CASCADE
);

